# Created using wingetcreate

PackageIdentifier: WiseCleaner.com.WiseCare365
PackageVersion: 5.6.6
PackageLocale: en-US
Publisher: WiseCleaner.com
PackageName: Wise Care 365
License: GNU GNU General Public License v3.0
ShortDescription: Clean registry and junk files from your PCs. Protect your privacy and make your PCs more secure. Provide a better option for optimizing and accelerating your computer!
ManifestType: defaultLocale
ManifestVersion: 1.0.0
